# Generated by Django 5.0.6 on 2024-05-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('link', models.CharField(max_length=600)),
                ('file', models.FileField(upload_to='media/')),
                ('data', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('Uzb', 'Uzb'), ('Markaziy osiyo', 'Markaziy osiyo'), ('Pul', 'Pul'), ('Dunyo', 'Dunyo'), ('Madaniyat', 'Madaniyat'), ('Sport', 'Sport'), ('Multimedia', 'Multimedia'), ('lifestyle', 'lifestyle')], max_length=200)),
            ],
        ),
    ]
